# Generated by Django 5.2.12 on 2026-07-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_preferred_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='preferred_integration',
            field=models.CharField(choices=[('anthropic', 'Anthropic')], default='anthropic', max_length=20),
        ),
    ]
