# Generated by Django 5.2.12 on 2026-07-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_preferred_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='credits_remaining',
            field=models.IntegerField(default=100),
        ),
    ]
