# Generated by Django 5.2.12 on 2026-07-08 12:10

from django.db import migrations, models


def blank_emails_to_null(apps, schema_editor):
    # Multiple '' values violate a unique constraint on Postgres (unlike
    # multiple NULLs, which don't) — existing accounts with no email (e.g.
    # ones created before this field required one) must be converted before
    # the AlterField below can apply the constraint.
    CustomUser = apps.get_model('users', 'CustomUser')
    CustomUser.objects.filter(email='').update(email=None)


def null_emails_to_blank(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    CustomUser.objects.filter(email=None).update(email='')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_credits_remaining'),
    ]

    operations = [
        # 1) Relax the DB-level NOT NULL constraint first — the data
        # migration below can't write NULL until this runs.
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        # 2) Now safe to convert existing '' to NULL.
        migrations.RunPython(blank_emails_to_null, null_emails_to_blank),
        # 3) Only now is it safe to add the unique constraint — duplicate
        # '' values would have violated it.
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
