# Generated by Django 5.2.12 on 2026-07-08 13:09

from django.db import migrations, models


def verify_existing_users(apps, schema_editor):
    # Login is gated on email_verified as of this migration, but accounts
    # created before this feature existed never went through an email
    # confirmation step — mark them verified so they aren't retroactively
    # locked out. Only new registrations from here on are actually gated.
    CustomUser = apps.get_model('users', 'CustomUser')
    CustomUser.objects.update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(verify_existing_users, migrations.RunPython.noop),
    ]
