# Generated by Django 5.2.12 on 2026-07-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_oauth_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_seen_onboarding',
            field=models.BooleanField(default=False),
        ),
    ]
