# Generated by Django 5.1.7 on 2025-03-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='openai_thread_id',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='title',
        ),
        migrations.AddField(
            model_name='thread',
            name='conversation_state',
            field=models.JSONField(default=list),
        ),
    ]
