# Generated by Django 5.2.12 on 2026-07-02 12:41

from django.db import migrations, models


def backfill_thread_provider_and_model(apps, schema_editor):
    Thread = apps.get_model('threads', 'Thread')
    for thread in Thread.objects.select_related('assistant').all():
        thread.ai_provider = thread.assistant.ai_provider
        thread.model = thread.assistant.model
        thread.save(update_fields=['ai_provider', 'model'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_remove_thread_openai_thread_id_remove_thread_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='ai_provider',
            field=models.CharField(choices=[('anthropic', 'Anthropic')], default='anthropic', max_length=50),
        ),
        migrations.AddField(
            model_name='thread',
            name='model',
            field=models.CharField(default='claude-sonnet-5', max_length=100),
        ),
        migrations.RunPython(backfill_thread_provider_and_model, noop_reverse),
    ]
