# Generated by Django 5.2.12 on 2026-07-02 14:12

from django.db import migrations, models


def backfill_thread_title(apps, schema_editor):
    Thread = apps.get_model('threads', 'Thread')
    for thread in Thread.objects.filter(title=''):
        for turn in thread.conversation_state or []:
            if turn.get('role') == 'user':
                title = (turn.get('content') or '')[:100]
                if title:
                    thread.title = title
                    thread.save(update_fields=['title'])
                break


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0004_thread_ai_provider_and_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.RunPython(backfill_thread_title, noop_reverse),
    ]
