# Generated by Django 5.2.12 on 2026-07-02 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('threads', '0005_thread_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='projects.project'),
        ),
    ]
