# Generated by Django 5.2.12 on 2026-07-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0006_thread_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='ai_provider',
            field=models.CharField(choices=[('anthropic', 'Anthropic'), ('openai', 'OpenAI'), ('mistral', 'Mistral'), ('gemini', 'Gemini')], default='anthropic', max_length=50),
        ),
    ]
