# Generated by Django 5.2.12 on 2026-07-10 14:02

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        # Not a Django-inferred FK dependency — this app's VectorField columns
        # require the Postgres `vector` extension to already exist, which
        # librarian's own 0001_initial creates via VectorExtension(). Django
        # doesn't guarantee cross-app migration ordering without an explicit
        # dependency here; on a genuinely fresh DB, omitting this could let
        # this migration's CREATE TABLE run before the extension exists.
        # Deliberately NOT calling VectorExtension() again — it's a no-op if
        # already present, but depending on librarian's migration makes the
        # ordering correct rather than accidentally correct.
        ('librarian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveIntegerField()),
                ('storage_key', models.CharField(max_length=500)),
                ('thumbnail_storage_key', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFileChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='project_files.projectfile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_chunks', to='projects.project')),
            ],
            options={
                'ordering': ['file_id', 'chunk_index'],
                'constraints': [models.UniqueConstraint(fields=('file', 'chunk_index'), name='unique_chunk_index_per_file')],
            },
        ),
    ]
