# Generated by Django 5.1.7 on 2025-03-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
