# Generated by Django 5.1.7 on 2025-03-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0003_assistant_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='ai_provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('mistral', 'Mistral')], default='openai', max_length=50),
        ),
    ]
