# Generated by Django 5.1.7 on 2025-03-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0004_assistant_ai_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistant',
            name='openai_id',
        ),
        migrations.AddField(
            model_name='assistant',
            name='is_persistent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assistant',
            name='provider_assistant_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='assistant',
            name='supports_crud',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='ai_provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('mistral', 'Mistral'), ('claude', 'Claude'), ('gemini', 'Gemini')], default='openai', max_length=50),
        ),
    ]
