# Generated by Django 5.2.12 on 2026-03-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0005_remove_assistant_openai_id_assistant_is_persistent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='ai_provider',
            field=models.CharField(choices=[('anthropic', 'Anthropic'), ('openai', 'OpenAI'), ('mistral', 'Mistral'), ('gemini', 'Gemini')], default='anthropic', max_length=50),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='model',
            field=models.CharField(default='claude-sonnet-4-6', max_length=100),
        ),
    ]
