# Generated by Django 5.2.12 on 2026-07-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0006_alter_assistant_ai_provider_alter_assistant_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='ai_provider',
            field=models.CharField(choices=[('anthropic', 'Anthropic')], default='anthropic', max_length=50),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='model',
            field=models.CharField(default='claude-sonnet-5', max_length=100),
        ),
    ]
