# Generated by Django 5.2.12 on 2026-07-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0007_alter_assistant_ai_provider_alter_assistant_model'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assistant',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_persistent', True)),
                fields=('user',),
                name='unique_persistent_assistant_per_user',
            ),
        ),
    ]
