# Generated by Django 5.2.17 on 2026-09-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0009_alter_assistant_ai_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='role',
            field=models.CharField(blank=True, help_text="Short specialty label used for multi-agent delegation matching, e.g. 'accounting', 'customer communication'.", max_length=255),
        ),
    ]
