# Generated by Django 5.1.7 on 2025-03-14 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat_messages', '0001_initial'),
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='threads.thread'),
        ),
    ]
