# Generated by Django 5.2.12 on 2026-07-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='tool_calls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
