# Generated by Django 5.2.12 on 2026-07-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0003_message_tool_calls'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='input_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='output_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
