# Generated by Django 5.2.12 on 2026-07-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0004_message_input_tokens_message_output_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='estimated_cost_usd',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
