# Generated by Django 5.2.17 on 2026-08-28 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0005_message_estimated_cost_usd'),
        ('threads', '0007_alter_thread_ai_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingToolConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=255)),
                ('arguments', models.JSONField(default=dict)),
                ('user_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_tool_confirmations', to='threads.thread')),
            ],
        ),
    ]
