# Generated by Django 5.2.17 on 2026-09-10 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0006_pendingtoolconfirmation'),
        ('threads', '0007_alter_thread_ai_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_turns', to='threads.thread')),
            ],
        ),
        migrations.DeleteModel(
            name='PendingToolConfirmation',
        ),
    ]
