# Generated by Django 5.2.17 on 2026-09-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0007_pendingturn_delete_pendingtoolconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingturn',
            name='tool_calls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
