# Generated by Django 5.2.12 on 2026-07-27 12:58

from django.db import migrations

NAME = 'memory_extraction_system'
# Exact text moved from librarian/services.py::_EXTRACTION_SYSTEM_PROMPT --
# this migration's whole point is to make that constant's content live here
# instead, not to also change its wording.
CONTENT = (
    "Given one exchange between a user and an assistant, decide whether it contains any "
    "durable fact worth remembering about the user long-term (preferences, personal details, "
    "ongoing projects, decisions). Reply with one fact per line, each rewritten as a short "
    "standalone statement. If there is nothing worth remembering, reply with exactly NONE."
)


def seed(apps, schema_editor):
    PromptTemplate = apps.get_model('prompts', 'PromptTemplate')
    PromptTemplate.objects.create(name=NAME, version=1, content=CONTENT, is_active=True)


def remove_seed(apps, schema_editor):
    PromptTemplate = apps.get_model('prompts', 'PromptTemplate')
    PromptTemplate.objects.filter(name=NAME, version=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed, remove_seed),
    ]
