# Generated by Django 5.2.17 on 2026-08-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_client', '0002_mcpserver_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpserver',
            name='requires_confirmation',
            field=models.BooleanField(default=True),
        ),
    ]
