# Generated by Django 5.1.7 on 2025-03-14 08:32

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_type', models.CharField(choices=[('openai', 'OpenAI'), ('mistral', 'Mistral'), ('made', 'Made.com')], max_length=20)),
                ('encrypted_key', encrypted_model_fields.fields.EncryptedCharField()),
                ('encryption_key_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
