# Generated by Django 5.2.12 on 2026-07-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key_type',
            field=models.CharField(choices=[('anthropic', 'Anthropic')], max_length=20),
        ),
    ]
