# Generated by Django 5.2.12 on 2026-07-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0003_alter_apikey_key_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key_type',
            field=models.CharField(choices=[('anthropic', 'Anthropic'), ('openai', 'OpenAI'), ('mistral', 'Mistral'), ('gemini', 'Gemini')], max_length=20),
        ),
    ]
