"""
Django settings for backend_sparqhub_django project.

Generated by 'django-admin startproject' using Django 5.1.7.
"""

from pathlib import Path
from decouple import config
from datetime import timedelta

# Build paths inside the project
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY
SECRET_KEY = 'django-insecure-d)1#n6!ok@sap42rk$@0&@###dqpbj-oqs*#&e4z9inr%4vf!*'
DEBUG = True
ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Third-party keys (dev only)
OPENAI_API_KEY      = config('OPENAI_API_KEY', default='')
FIELD_ENCRYPTION_KEY= config('FIELD_ENCRYPTION_KEY', default='')

AUTH_USER_MODEL = 'users.CustomUser'


# Application definition
INSTALLED_APPS = [
    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'channels',
    'corsheaders',
    'encrypted_model_fields',
    'rest_framework.authtoken',
    'rest_framework_simplejwt.token_blacklist',
    # Your apps
    'core',
    'users',
    'assistants',
    'threads',
    'chat_messages',
    'automation',
    'user_settings',
    'librarian',
    'keys',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend_sparqhub_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend_sparqhub_django.wsgi.application'
ASGI_APPLICATION = 'backend_sparqhub_django.asgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE':   'django.db.backends.postgresql',
        'NAME':     config('DATABASE_NAME',     default='mydb'),
        'USER':     config('DATABASE_USER',     default='postgres'),
        'PASSWORD': config('DATABASE_PASSWORD', default='Zenith100+'),
        'HOST':     config('DATABASE_HOST',     default='db'),
        'PORT':     config('DATABASE_PORT',     default='5432'),
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE     = 'UTC'
USE_I18N      = True
USE_TZ        = True

# Static files
STATIC_URL           = 'static/'
STATIC_ROOT          = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE  = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Channels / Celery
CELERY_BROKER_URL               = 'redis://redis:6379/0'
broker_connection_retry_on_startup = True
CELERY_RESULT_BACKEND           = 'redis://redis:6379/0'
CELERY_ACCEPT_CONTENT           = ['json']
CELERY_TASK_SERIALIZER          = 'json'
CELERY_RESULT_SERIALIZER        = 'json'

# Channels layer
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG':  { 'hosts': [('redis', 6379)], },
    },
}

# CORS & CSRF
CSRF_COOKIE_HTTPONLY = False          # default
CSRF_COOKIE_SECURE   = True           # over HTTPS in prod
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
]
SESSION_COOKIE_HTTPONLY = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS  = ['http://localhost:3000']

# Simple JWT
SIMPLE_JWT = {
    'AUTH_COOKIE':          'access_token',
    'AUTH_COOKIE_SECURE':    False,
    'AUTH_COOKIE_HTTP_ONLY': True,
    'AUTH_COOKIE_SAMESITE':  'Lax',
    'ACCESS_TOKEN_LIFETIME':     timedelta(minutes=5),
    'REFRESH_TOKEN_LIFETIME':    timedelta(days=1),
    'ROTATE_REFRESH_TOKENS':     True,
    'BLACKLIST_AFTER_ROTATION':  True,
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'users.authentication.CookieJWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'loggers': {
        'chat_messages': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
}
